config/routes.rb
Rails.application.routes.draw do

  # ______________________________________________________

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # ______________________________________________________

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations", sessions: "sessions" }
  # devise_for :users, :controllers => {:registrations => "registrations"}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# __________________________________________________________________

  resources :profiles, except: [ :destroy ]
# __________________________________________________________________


  get 'play/:questionnaire_id', to: 'questionnaires#play', as: :play


  get 'random_questionnaire', to: 'questionnaires#random_questionnaire_for_user', as: :random_questionnaire



   resources :questionnaires, only: [ :index, :show, :new, :create ] do

    resources :questions do
      resources :responses, only: [:new, :create]
    end
    resources :results, only: [ :new, :create, :edit, :update, :show ]

    resources :prizes


   end

  resources :questions, only: [:show] do
    resources :answers, except: [ :show ]
    resources :responses, except: [:new, :create]
    get 'intro', to: 'responses#intro'
  end

  resources :answers, only: [ :show ] do
  end
#   resources :questionnaires, only: [ :index, :show, :new, :create ] do
#     resources :results, only: [ :new, :create ]
#     resources :prizes, only: [ :index, :show ]

#     resources :questions, only: [:show ] do
#       resources :answers, only: [ :show ]
#     end
#   end

#   resources :questionnaires, only: [ :new, :create ] do
#     resources :prizes, except: [ :index, :show ]
#     resources :questions, except: [ :show ] do
#       resources :answers, except: [ :show ]
#     end
#   end

# __________________________________________________________________

# __________________________________________________________________

end

app/models/2questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :profile
  has_many :profiles, through: :results
  has_many :prizes, through: :prize_pools
  has_many :questions
  has_many :answers, through: :questions


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prize.rb
class Prize < ApplicationRecord
  belongs_to :questionnaire
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :questionnaires
  has_many :responses
  has_many :answers, through: :responses
  has_many :results

  #this is for activeAdmin
  def name
    self.user.email
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers
end

app/models/questionaire.rb
class Questionaire < ApplicationRecord
  belongs_to :profile
  has_many :profiles, through: :results
  has_many :prizes, through: :prize_pools
  has_many :questions
  has_many :answers, through: :questions


end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :profile
  has_many :results
  has_many :profiles, through: :results
  has_many :prizes
  has_many :questions
  has_many :answers, through: :questions

end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :profile
  belongs_to :answer
  has_one :questionnaire

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :profile
  belongs_to :questionnaire
  belongs_to :prize 
end

app/models/user.rb
class User < ApplicationRecord

  has_one :profile

  validates :email, uniqueness: true
  # validates :email, format: { with: /\A.*@.*\.\z/ }, uniqueness: true

  validates :password, length: { minimum: 6 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

      def self.find_for_facebook_oauth(auth)
       user_params = auth.slice(:provider, :uid)
       user_params.merge! auth.info.slice(:email, :first_name, :last_name)
       user_params[:facebook_picture_url] = auth.info.image
       user_params[:token] = auth.credentials.token
       user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
       user_params = user_params.to_h

       user = User.where(provider: auth.provider, uid: auth.uid).first
       user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
       if user
         user.update(user_params)
       else
         user = User.new(user_params)
         user.password = Devise.friendly_token[0,20]  # Fake password for validation
         user.save
       end

       return user
      end

      def name
        self.email
      end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- OG META DATA -->
    <!-- This is the metadata for FB sharing - Check what gets scraped by FB at https://developers.facebook.com/tools/debug/sharing/  -->
    <!-- You can ignore the App_id error as it is only for FB apps -->

    <!-- og:title - up to 55 chars -->
    <meta property="og:title" content="Answer this - Share your opinion and win">
    <!-- og:type - shouldn;t need to change this -->
    <meta property="og:type"   content="website" />
    <!-- og:image should be in public folder - not app/image. It should be 1200px*633px and in jpg format - a screen shot is OK-->
    <meta property="og:image" content="http://www.answerthis.nl/facebook-image.jpg">
    <!-- og:description - up to 160 chars -->
    <meta property="og:description" content="Answer 5 questions and win great prizes.">
    <!-- og:site name -->
    <meta property="og:site_name" content="Answer This"/>
    <!-- og:url This is the url that will actually be shared on facebook - This is useful if they share from one page (eg /AboutUs) and you want them to share the index page on FB-->
    <meta property="og:url" content="http://www.answerthis.nl"/>
    <!-- END OG META -->

    <meta name="theme-color" content="#473B77">
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Answer this - Share your opinion and win</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <!-- app/views/layouts/application.html.erb -->
    <%= render 'shared/navbar' %>
    <!-- app/views/layouts/application.html.erb -->
    <%= render 'shared/flashes' %>
    <%= yield %>

    <!-- ***THIS IS THE WARNING THAT THERE ARE NO PRIZES!******************* -->
    <%= render 'shared/corner_label' %>
    
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Answer This!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>

  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/shared/_corner_label.html.erb
<div id="corner_label">
  <h1>TESTING</h1>
  <p>
    There are no prizes to be won
  </p>
</div>

<style>
  #corner_label {
    position: absolute;
    top: 0px;
    left: 0px;
    border: 2px solid black;
    transform-origin: 50% top;
    transform: translate(-40%, 90%) rotate(-45deg);
    text-align: center;
    color: white;
    background-color: rgba(71, 59, 119, 0.5);
    padding: 0px 300px 0px 300px;
  }
  #corner_label h1 {
    padding: 10px;
    margin: 0px;
  }
</style>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "answer_this_logo.png", class: ".navbar-wagon-brand"%>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% avatar_url = current_user.facebook_picture_url || "profile.svg" %>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to profile_path(current_user.id) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= mail_to "hello@answerthis.nl", subject: "I love your app!!", :body => "I realy love your app! I already won an iphone, a car and a holiday to the Maldives!!" do %>
            <i class="fa fa-envelope"></i>  <%= t(".profile", default: "Contact") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

    <!-- Button (call-to-action) -->
    <% if current_user %>
    <% if current_profile.is_client == 1 %>
    <%= link_to t(".top_call_to_action", default: "Create Questionnaire"), new_questionnaire_path, class: "navbar-wagon-button" %>
    <% else %>
    <%= link_to t(".top_call_to_action", default: "Take questionnaire!"), new_questionnaire_result_path(Questionnaire.last.id), class: "navbar-wagon-button" %>

    <% end %>
    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->

  <div class="navbar-wagon-item hidden-md hidden-lg">
  <% if user_signed_in? %>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to profile_path(current_user.id) do %>
          <i class="fa fa-user dropdown-icon"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to root_path do %>
          <i class="fa fa-home dropdown-icon"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign dropdown-icon-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
    <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>