config/routes.rb
Rails.application.routes.draw do

  # ______________________________________________________

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # ______________________________________________________

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations", sessions: "sessions" }
  # devise_for :users, :controllers => {:registrations => "registrations"}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# __________________________________________________________________

  resources :profiles, except: [ :destroy ]
# __________________________________________________________________


  get 'play/:questionnaire_id', to: 'questionnaires#play', as: :play


  get 'random_questionnaire', to: 'questionnaires#random_questionnaire_for_user', as: :random_questionnaire



   resources :questionnaires, only: [ :index, :show, :new, :create ] do

    resources :questions do
      resources :responses, only: [:new, :create]
    end
    resources :results, only: [ :new, :create, :edit, :update, :show ]

    resources :prizes


   end

  resources :questions, only: [:show] do
    resources :answers, except: [ :show ]
    resources :responses, except: [:new, :create]
    get 'intro', to: 'responses#intro'
  end

  resources :answers, only: [ :show ] do
  end
#   resources :questionnaires, only: [ :index, :show, :new, :create ] do
#     resources :results, only: [ :new, :create ]
#     resources :prizes, only: [ :index, :show ]

#     resources :questions, only: [:show ] do
#       resources :answers, only: [ :show ]
#     end
#   end

#   resources :questionnaires, only: [ :new, :create ] do
#     resources :prizes, except: [ :index, :show ]
#     resources :questions, except: [ :show ] do
#       resources :answers, except: [ :show ]
#     end
#   end

# __________________________________________________________________

# __________________________________________________________________

end

app/models/2questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :profile
  has_many :profiles, through: :results
  has_many :prizes, through: :prize_pools
  has_many :questions
  has_many :answers, through: :questions


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prize.rb
class Prize < ApplicationRecord
  belongs_to :questionnaire
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :questionnaires
  has_many :responses
  has_many :answers, through: :responses
  has_many :results

  #this is for activeAdmin
  def name
    self.user.email
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers
end

app/models/questionaire.rb
class Questionaire < ApplicationRecord
  belongs_to :profile
  has_many :profiles, through: :results
  has_many :prizes, through: :prize_pools
  has_many :questions
  has_many :answers, through: :questions


end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :profile
  has_many :results
  has_many :profiles, through: :results
  has_many :prizes
  has_many :questions
  has_many :answers, through: :questions

end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :profile
  belongs_to :answer
  has_one :questionnaire

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :profile
  belongs_to :questionnaire
  belongs_to :prize 
end

app/models/user.rb
class User < ApplicationRecord

  has_one :profile

  validates :email, uniqueness: true
  # validates :email, format: { with: /\A.*@.*\.\z/ }, uniqueness: true

  validates :password, length: { minimum: 6 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

      def self.find_for_facebook_oauth(auth)
       user_params = auth.slice(:provider, :uid)
       user_params.merge! auth.info.slice(:email, :first_name, :last_name)
       user_params[:facebook_picture_url] = auth.info.image
       user_params[:token] = auth.credentials.token
       user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
       user_params = user_params.to_h

       user = User.where(provider: auth.provider, uid: auth.uid).first
       user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
       if user
         user.update(user_params)
       else
         user = User.new(user_params)
         user.password = Devise.friendly_token[0,20]  # Fake password for validation
         user.save
       end

       return user
      end

      def name
        self.email
      end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [:new, :destroy, :create]

  def index
    # @questionnaire = Answer.find(params[:questionnaire_id]).question.questionnaire
    @answer = Answer.find(params[:answer_id])
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @over_limit = @question.answers.length > 4 ? true : false
  end

  def create
    answer = Answer.new(answer_params)
    answer.question = @question
    answer.save
    redirect_to new_question_answer_path(@question)
  end

  def edit
  end

  def update
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to new_question_answer_path(@question)
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end

  def new
  end

  def create
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/prize_pools_helper.rb
module PrizePoolsHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/answers/_answers_form.html.erb
<div class="form-wrapper">
  <div class="create-form">
  <% if @question.answers.length < 4 %>
    <%= simple_form_for [@question, @answer], class: "form-control" do |f| %>
      <%= f.input :body, label: 'Answer', class: "form_field", placeholder: "blabla", required: true %>
    <%= f.submit class: "start-btn" %>
    <% end %>
  <% else %>

  <% end %>
  </div>
</div>


<% if @question.answers.length > 0 %>
  <h3>Current answers</h3>
<% end %>

<div class="created-answers">
  <% @question.answers.order(created_at: :desc).each do |answer| %>
    <div class="created-answer">
      <pre>
        <%= answer.body %>
      </pre>
      <%= link_to 'Destroy', question_answer_path(@question, answer),
                data: {confirm: 'Are you sure?'}, method: :delete, class: 'start-btn' %>
    </div>
  <% end %>
</div>

<% if @question.answers.length > 0 %>
  <hr class="orange-line-small">
<% end %>

<% if @over_limit %>
  <%flash[:alert] = "There can only be 4 answers to a question..." %>
<%end%>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/new.html.erb
<div class="text-center theme">
  <hr class="orange-line">
  <h1 style="padding-top: 1.5%;">Add answers for:</strong></h1>
  <h2><strong><%= @question.body %></h2>
  <div style="margin-bottom: 2%; margin-top: 2%;">
    <%= link_to_unless(@question.answers.length > 4, "Next question", new_questionnaire_question_path(@question.questionnaire), class: "start-btn") %>

    <%= link_to_unless(@question.answers.length > 4, "Show Questionnaire", questionnaire_path(@question.questionnaire), class: "start-btn") %>
  </div>
  <hr class="orange-line-small"></hr>
  <%=render "answers_form"%>
</div>

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>