config/routes.rb
Rails.application.routes.draw do

  # ______________________________________________________

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # ______________________________________________________

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations", sessions: "sessions" }
  # devise_for :users, :controllers => {:registrations => "registrations"}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# __________________________________________________________________

  resources :profiles, except: [ :destroy ]
# __________________________________________________________________


  get 'play/:questionnaire_id', to: 'questionnaires#play', as: :play


  get 'random_questionnaire', to: 'questionnaires#random_questionnaire_for_user', as: :random_questionnaire



   resources :questionnaires, only: [ :index, :show, :new, :create ] do

    resources :questions do
      resources :responses, only: [:new, :create]
    end
    resources :results, only: [ :new, :create, :edit, :update, :show ]

    resources :prizes


   end

  resources :questions, only: [:show] do
    resources :answers, except: [ :show ]
    resources :responses, except: [:new, :create]
    get 'intro', to: 'responses#intro'
  end

  resources :answers, only: [ :show ] do
  end
#   resources :questionnaires, only: [ :index, :show, :new, :create ] do
#     resources :results, only: [ :new, :create ]
#     resources :prizes, only: [ :index, :show ]

#     resources :questions, only: [:show ] do
#       resources :answers, only: [ :show ]
#     end
#   end

#   resources :questionnaires, only: [ :new, :create ] do
#     resources :prizes, except: [ :index, :show ]
#     resources :questions, except: [ :show ] do
#       resources :answers, except: [ :show ]
#     end
#   end

# __________________________________________________________________

# __________________________________________________________________

end

app/models/2questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :profile
  has_many :profiles, through: :results
  has_many :prizes, through: :prize_pools
  has_many :questions
  has_many :answers, through: :questions


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prize.rb
class Prize < ApplicationRecord
  belongs_to :questionnaire
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :questionnaires
  has_many :responses
  has_many :answers, through: :responses
  has_many :results

  #this is for activeAdmin
  def name
    self.user.email
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers
end

app/models/questionaire.rb
class Questionaire < ApplicationRecord
  belongs_to :profile
  has_many :profiles, through: :results
  has_many :prizes, through: :prize_pools
  has_many :questions
  has_many :answers, through: :questions


end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :profile
  has_many :results
  has_many :profiles, through: :results
  has_many :prizes
  has_many :questions
  has_many :answers, through: :questions

end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :profile
  belongs_to :answer
  has_one :questionnaire

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :profile
  belongs_to :questionnaire
  belongs_to :prize 
end

app/models/user.rb
class User < ApplicationRecord

  has_one :profile

  validates :email, uniqueness: true
  # validates :email, format: { with: /\A.*@.*\.\z/ }, uniqueness: true

  validates :password, length: { minimum: 6 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

      def self.find_for_facebook_oauth(auth)
       user_params = auth.slice(:provider, :uid)
       user_params.merge! auth.info.slice(:email, :first_name, :last_name)
       user_params[:facebook_picture_url] = auth.info.image
       user_params[:token] = auth.credentials.token
       user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
       user_params = user_params.to_h

       user = User.where(provider: auth.provider, uid: auth.uid).first
       user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
       if user
         user.update(user_params)
       else
         user = User.new(user_params)
         user.password = Devise.friendly_token[0,20]  # Fake password for validation
         user.save
       end

       return user
      end

      def name
        self.email
      end

end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController



  def index
    @questionnaires = Questionnaire.all
  end

  def show
    @questionnaire = Questionnaire.find(params[:id])
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    @questionnaire.profile_id = current_profile.id
    @questionnaire.save!
    redirect_to new_questionnaire_question_path(@questionnaire.id)
  end

  def edit

  end

  def update
    @questionnaire.title = questionnaire_params[:title]
    @questionnaire.body = questionnaire_params[:body]
    @questionnaire.save!
    flash[:notice] = "Updated questionnaire"
    redirect_to new_questionnaire_question_path(@questionnaire.id)
  end

  def play
    @questionnaire = Questionnaire.first # should be the @random_questionnaire from the pages#home
    @questions = Question.where(questionnaire_id: @questionnaire.id)
  end

  def edit
  end


  def update

  end

  # def choose_prize
    # @questionnaire = Questionnaire.find(params[:questionnaire_id])
    # @result = Result.find(params[:result_id])
    # @prizes = Prize.where(questionnaire_id: @questionnaire.id)
  # end

  # def completed_questionnaires
  #   # code to generate a random questionnaire
  #   redirect_to random_questionnaire_path
  # end

  def random_questionnaire_for_user

    @questionnaire = Questionnaire.find(1)
    redirect_to new_questionnaire_result_path(@questionnaire.id)



    # Uncompleted logic to generate random questionnaire

    @profileresults = Result.where(profile_id: current_profile.id, status: !0)
    raise
    @completed_questionnaire_ids = []
    @profileresults.each do |result|
      @completed_questionnaire_id = result.questionnaire_id
      @completed_questionnaire_ids << @completed_questionnaire_id
    end
    @random_completed_questionnaire_id = @completed_questionnaire_ids.sample
    @uncompleted_questionnaire_id = Question.find_by id: !@random_completed_questionnaire_id
    @questionnaire = Questionnaire.find(@uncompleted_questionnaire_id)

  end

  private

# POSSIBLE set_questonnaire/set_result METHOD

  def questionnaire_params
    params.require(:questionnaire).permit(:title, :description, :profile_id)

  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/prize_pools_helper.rb
module PrizePoolsHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/questionnaires/_questionnaire_description.html.erb
<div class="hidden questionnaire-description-div">
  <p><%= @questionnaire.description %><p>
  <button class="btn btn-primary btn-md" id="play-btn">Let's play!</button>
</div>

app/views/questionnaires/_questions.html.erb
<div class="questions-div hidden text-center">
  <h3>List of questions and their answers</h3>
  <ul id="questions-list">
    <% @questions.each do |question| %>
      <li>
        <div id="question-<%= question.id %>-div" class="question-div text-center healthy-bottom-padding">

          <h4><%= question.title %></h4>

          <h5><%= question.body %></h5>

          <ul id="answers-list">

            <% @answers = Answer.where(question_id: question.id) %>
            <% @answers.each do |answer| %>
              <li>
                <button class="btn btn-info btn-md"><%= answer.body %></button>
              </li>
            <% end %>

          </ul>

        </div>
      </li>
    <% end %>
  </ul>

  <button class="submit-questionnaire-btn btn btn-danger btn-md">Submit questionnaire</button>

</div>

app/views/questionnaires/_spin_result.html.erb
<div class="spin-result-div text-center hidden">


  <div class="spin-result">
    <h1>Spin result</h1>
  </div>

  <!-- <button class="btn btn-danger btn-md finish-btn">Finito</button> -->
  <%= link_to 'Finito', root_path, { class: "btn btn-danger btn-md" } %>

</div>

app/views/questionnaires/_spinner.html.erb
<div class="spinner-div text-center hidden">

  <div class="spinner text-center">
    <h4>Spinner</h4>
  </div>

  <button class="btn btn-danger btn-md" id="spin-btn">Spin</button>

</div>

app/views/questionnaires/create.html.erb
<h1>Questionnaires#create</h1>
<p>Find me in app/views/questionnaires/create.html.erb</p>

app/views/questionnaires/edit.html.erb
<h1>edit page Questionnaire</h1>

app/views/questionnaires/index.html.erb
<div class="theme text-center">

  <h1>Questionnaires</h1>
  <p>Find a list of your questionnairs here:</p>

  <% number = current_profile.questionnaires.count %>
  <% if number == 0 %>
  <h1 style="padding-top: 2%; padding-bottom: 2%;">You have <strong><%= number %></strong> questionnaires</h1>
  <% elsif number == 1 %>
  <h1 style="padding-top: 2%; padding-bottom: 2%;">You have <strong><%= number %></strong> questionnaire</h1>
  <% else %>
  <h1 style="padding-top: 2%; padding-bottom: 2%;">You have <strong><%= number %></strong> questionnaires</h1>
  <% end %>
  <hr class="orange-line-small">
  <div class="questions-list-div">
    <ul class="questions-list">
      <% current_profile.questionnaires.each_with_index do |questionnaire, index| %>
        <div class="questionnaire-card">
          <li class="questions-list-item">
            <%= link_to questionnaire.title, questionnaire_path(questionnaire), class: 'link' %>
          </li>
          <% if number > 1 %>
            <hr class="purp-line">
          <% end %>
        </div>
      <% end %>
    </ul>
  </div>


  <br>
  <%= link_to "Back home", root_path, class: "start-btn" %>
</div>

app/views/questionnaires/new.html.erb
<div class="theme text-center">

  <h1> New Questionnaire</h1>
  <hr class="orange-line-small">

  <div class="form-wrapper">
    <div class="create-form">
      <%= simple_form_for @questionnaire do |f| %>
        <%= f.input :title, label: 'Title', class: "form_field", required: true %>
        <%= f.input :description, label: 'Description', class: "form_field", required: true %>
        <%= f.submit class: 'start-btn' %>
      <% end %>
    </div>
  </div>

  <%= link_to "Back home", root_path, class: "start-btn" %>

</div>

app/views/questionnaires/play.html.erb
<div class="active-questionnaire-container">
  <%= render 'choose_prize' %>
   ________________________________

  <%= render 'questionnaire_description' %>
  <%= render 'questions' %>
  <%= render 'spinner' %>
  <%= render 'spin_result' %>
</div>

app/views/questionnaires/show.html.erb
<div class="text-center theme">
<div>
  <h1><%= @questionnaire.title%></h1>
  <hr class="orange-line-small">
  <br>
  <p class="lighter-text" style="max-width: 550px; text-align: left; margin: auto;"><%= @questionnaire.description%></p>
  <div class="button">
    <%= link_to "All questionnaires", questionnaires_path(@questionnaire), class: "purple-btn" %>
  </div>

  <div class="title-div">
    <h2>Questions</h2>
  </div>

  <div class="questions-div">

    <% question_number = 0 %>

    <ul class="question-list">

      <% @questionnaire.questions.each do |question| %>
      <% question_number += 1 %>
      <% question_number.to_s %>
      <li class="question-list-item">
        <div class="question-card">
          <h3><%= question_number %>: <%= question.title %></h3>
          <p class="lighter-text"><%= question.body %></p>
          <ul class="answers-list">
            <% question.answers.each do |answer| %>
            <li><%= answer.body %></li>
            <% end %>
          </ul>
        </div>
      </li>
      <% end %>

    </ul>
  </div>


  <h2>Prizes</h2>
  <hr class="orange-line">
  <div class="button">
    <%= link_to "Add prizes", new_questionnaire_prize_path(@questionnaire), class: "purple-btn" %>
  </div>


  <div class="prizes-div">
    <% @questionnaire.prizes.each_with_index do |prize, index| %>
    <div class="prize-card">
      <h3><%= prize.title %></h3>
      <p class="lighter-text"><%= prize.description %></p>

      <ul class="prize-detail-list">
        <li><strong>Value:</strong> <%= prize.value %></li>
        <li><strong>Quantity:</strong> <%= prize.quantity_remaining %></li>
        <li><strong>Probability:</strong> <%= prize.win_probability %></li>
        <li><strong>Voucher code:</strong> <%= prize.voucher_code %></li>
      </ul>

    </div>
    <% end %>
  </div>

  <hr class="orange-line" style="margin-bottom: 5% !important;">


</div>